<?php
/**
 * Plugin Name:       WooCommerce Default Ordering
 * Plugin URI:        
 * Description:       Orders the default WooCommerce product listing by menu order, then title or specified from settings.
 * Version:           1.1.2
 * Author:            Josiah Troup
 * Author URI:        
 * Text Domain:       wdo
 * Domain Path:       /languages
 *
 * Generated by WordPress Plugin Generator v1.1.1 (wordpressplugingenerator.com)
 *
 */

// Prevent to access the file from outside of WordPress
if(!defined('ABSPATH')) {
	exit;
}
if(!function_exists('wp_get_current_user')) {
	include(ABSPATH . 'wp-includes/pluggable.php');
}

class wdo_Loader {
	public $config = [
		'name' => 'WooCommerce Default Ordering',
		'version' => '1.1.2',
		'textDomain' => 'wdo',
		'textDomainPath' => 'languages',
		'slug' => 'woocommerce-default-ordering',
		'prefix' => 'wdo',
		'prefixSeparator' => '_',
	];
	
	//
	public function __construct() {
		self::init();

		self::start();
	}

	/**
	 * Initialize the plugin
	 */
	private function init() {
	}

	
	/**
	 * Deactivates the plugin due to the missing requirements.
	 */
	public function deactivate() {
		if(current_user_can('activate_plugins') && is_plugin_active(plugin_basename(__FILE__))) {
			deactivate_plugins(plugin_basename(__FILE__));
	
			// Hide the default "Plugin activated" notice
			if(isset($_GET['activate'])) {
				unset($_GET['activate']);
			}
		}
	}

	/**
	 * Starting the plugin.
	 */
	public function start() {
		require_once plugin_dir_path(__FILE__) . 'classes/plugin.php';
		$plugin = new wdo_Plugin($this->config);

		register_activation_hook(__FILE__, [&$plugin, 'activate']);
		register_deactivation_hook(__FILE__, [&$plugin, 'deactivate']);
	}
}

$wdo = new wdo_Loader();
